Generate `<p>`, not `<p/>`, in javadoc, self-closing element not allowed
Since JDK 8 javadoc requires strict HTML 4. A self-closing `<p/>`
is no longer allowed and javadoc fails with
```
error: self-closing element not allowed
```

For details see https://stackoverflow.com/q/26049329

Replacing `<p/>` with `<p>` fixes the error.